name: 'y2cl-setup'
description: 'Setup action for Y2CL'
author: 'Alexander Richards'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  project:
    description: 'Which project template to use.'
    required: true
  src_dir:
    description: "The directory with the source to copy."
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout Tests
    uses: actions/checkout@v3
    with:
      repository: ImperialCollegeLondon/Y2CL_ProjectA_Template
      ref: main
  - name: Checkout user code
    uses: actions/checkout@v3
    with:
      path: "user_code"
  - name: Copy user code into local install
    run: cp -R ./user_code/$INPUT_SRC_DIR/* ./$INPUT_SRC_DIR/
    shell: bash
  - name: Delete redundant user code directory
    run: rm -rf ./user_code
    shell: bash
  - name: Update Python package tools
    run: sudo python -m pip install --upgrade pip setuptools wheel
    shell: bash
  - name: Install local code in edit mode ready for testing
    run: python -m pip install --user -e .
    shell: bash
