name: 'y2cl-setup'
description: 'Setup action for Y2CL'
author: 'Alexander Richards'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  project:
    description: 'Which project template to use.'
    required: true
  src_dir:
    description: "The directory with the source to copy."
    required: true
  python_version:
    description: "Python version."
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout Tests
    uses: actions/checkout@v3
    with:
      repository: "ImperialCollegeLondon/Y2CL_${{ inputs.project }}_Template"
      ref: main
  - name: Checkout user code
    uses: actions/checkout@v3
    with:
      path: "user_code"
  - name: Copy user code into local install
    run: "cp -R ./user_code/${{ inputs.src_dir }}/* ./${{ inputs.src_dir }}/"
    shell: bash
  - name: Delete redundant user code directory
    run: rm -rf ./user_code
    shell: bash
  - name: Setup Python
    uses: actions/setup-python@v5.0.0
    with:
      python-version: "${{ inputs.python_version }}"
  - name: Update Python package tools
    run: "sudo python3 -m pip install --upgrade pip setuptools wheel"
    shell: bash
  - name: Install local code in edit mode ready for testing
    run: "python3 -m pip install --user -e ."
    shell: bash
